# Generated by Django 4.2.3 on 2023-07-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scrap_request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default=None, max_length=50)),
                ('quantity', models.IntegerField(default=10)),
            ],
        ),
    ]
